export const services = [
  {
    slug: 'hudanalys-stockholm',
    title: 'Hudanalys',
    pageTitle: 'Kostnadsfri hudanalys i Stockholm',
    summary: '30 minuter kostnadsfri hudkonsultation för dig som vill hitta rätt hudbehandling.',
    intro:
      'Det kan vara svårt att själv avgöra vilken ansiktsbehandling som är rätt. Akne, pigmentering, känslighet, pormaskar, torrhet och ojämn hudstruktur kan se liknande ut på ytan men huden kan ändå behöva olika typer av behandling. Hos Dermalaser kan nya kunder börja med en personlig hudanalys. Hudanalysen tar cirka 30 minuter och kostar 0 kr.',
    points: [
      'Akne eller oren hud',
      'Känslig eller reaktiv hud',
      'Pigmentering eller ojämn hudton',
      'Tilltäppta porer eller ojämn hudstruktur',
      'Hud som känns obalanserad, trött eller glåmig',
    ],
    items: [
      'Hudanalys - 30 minuter, 0 kr',
      'Personlig genomgång av hudens aktuella tillstånd',
      'Rådgivning utifrån dina mål och tidigare erfarenheter',
      'Rekommendation av rätt behandlingsupplägg',
    ],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: 'Cirka 30 minuter',
      paKliniken: 'Personlig konsultation med hudanalys',
      tillbakaTillVardagen: 'Direkt',
      antalBehandlingar: 'Ett kostnadsfritt första steg för nya kunder',
      risker: 'Inga behandlingar utförs utan att du först fått tydlig rådgivning',
      efterbehandling: 'Du får rekommendationer anpassade efter din hud',
      undvik: 'Du behöver inte förbereda något särskilt',
      pris: '0 kr för nya kunder',
      betalning: 'Kostnadsfri konsultation',
    },
    faq: [
      { question: 'Kostar hudanalysen något?', answer: 'Nej. Hudanalysen för nya kunder är kostnadsfri.' },
      { question: 'Hur lång tid tar den?', answer: 'Hudanalysen tar cirka 30 minuter.' },
      { question: 'Måste jag veta vilken behandling jag vill göra?', answer: 'Nej. Hudanalysen är till för dig som vill ha hjälp att välja rätt behandling.' },
      { question: 'Kan jag boka för akne eller pigmentering?', answer: 'Ja. Akne, känslighet, pigmentering, porer och ojämn struktur är exempel på områden vi kan diskutera.' },
      { question: 'Kan behandling göras direkt efter?', answer: 'Det beror på vilken behandling som rekommenderas och om det finns tid. Utgångspunkten är alltid att rätt behandling väljs först.' },
    ],
  },
  {
    slug: 'aknebehandling-stockholm',
    title: 'Akne & oren hud',
    pageTitle: 'Aknebehandling i Stockholm för akne, finnar och oren hud',
    summary: 'Personligt anpassad aknebehandling i Stockholm för finnar, pormaskar, tilltäppt hud och vuxenakne. 45 minuter, 795 kr.',
    intro:
      'Akne kan förekomma både under tonåren och i vuxen ålder och kan visa sig som finnar, pormaskar, tilltäppta porer, inflammation och återkommande utbrott. Dermalasers aknebehandling anpassas efter hudens aktuella behov med fokus på att rengöra, lugna och stödja en mer stabil hud över tid. Behandlingen tar 45 minuter och kostar 795 kr.',
    points: [
      'Pormaskar och tilltäppta porer',
      'Inflammerade utbrott och återkommande finnar',
      'Vuxenakne runt haka, käklinje och kinder',
      'Oren och obalanserad hud',
      'Rodnad, märken och förändrad hudstruktur efter akne',
    ],
    items: [
      'Aknebehandling - 45 minuter, 795 kr',
      'Individuellt upplägg för akne, finnar och oren hud',
      'Rengöring och lugnande hudvård efter hudens behov',
      'Råd om hudvård mellan behandlingarna',
    ],
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: '45 minuter',
      paKliniken: 'Behandlingen anpassas efter hudens aktuella tillstånd',
      tillbakaTillVardagen: 'Direkt, viss rodnad kan förekomma',
      antalBehandlingar: 'Varierar med hudens tillstånd och hur den svarar på behandling',
      risker: 'Tillfällig rodnad eller känslighet kan förekomma',
      efterbehandling: 'Följ rekommenderad hudvård och undvik att överbehandla huden',
      undvik: 'Aggressiv rengöring, överdriven exfoliering och för många aktiva produkter',
      pris: '795 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Vilken behandling är bäst mot akne?', answer: 'Det finns ingen metod som är bäst för all akne. Valet beror på om huden är inflammerad, tilltäppt, känslig eller kombinerar flera problem.' },
      { question: 'Behandlar ni vuxenakne?', answer: 'Ja. Tjänsten är avsedd för både tonårsakne och vuxenakne.' },
      { question: 'Kan behandlingen hjälpa mot pormaskar?', answer: 'Den kan anpassas för tilltäppt och oren hud. Hydrafacial, Carbon Peel och vissa peelingar kan också vara relevanta.' },
      { question: 'Hur lång är behandlingen?', answer: 'Behandlingen tar 45 minuter.' },
      { question: 'Vad kostar den?', answer: 'Aknebehandlingen kostar 795 kr.' },
      { question: 'Hur många behandlingar behövs?', answer: 'Det varierar med hudens tillstånd och hur den svarar på behandling.' },
      { question: 'Vad gör jag om jag inte vet om detta är rätt behandling?', answer: 'Boka kostnadsfri hudanalys först så hjälper vi dig att välja rätt behandling.' },
    ],
  },
  {
    slug: 'kanslig-hud-stockholm',
    title: 'Känslig & reaktiv hud',
    pageTitle: 'Behandling för känslig och reaktiv hud i Stockholm',
    summary: 'Behandling för känslig, torr och reaktiv hud i Stockholm med fokus på hudbarriär, rodnad, irritation och balans. 45 minuter, 695 kr.',
    intro:
      'Känns huden ofta röd, varm, irriterad, torr eller stram? Reagerar den snabbt på produkter, väder, stress eller behandlingar? Känslig hud behöver ofta ett skonsammare och mer genomtänkt upplägg. Dermalasers behandling fokuserar på att lugna huden, stärka hudbarriären och återställa balans och komfort. Behandlingen tar 45 minuter och kostar 695 kr.',
    points: [
      'Rodnad, värmekänsla och irritation',
      'Torr, stram eller fuktfattig hud',
      'Hud som snabbt reagerar på produkter eller väder',
      'Stressad eller försvagad hudbarriär',
      'Obalanserad hud med låg tolerans',
    ],
    items: [
      'Behandling för känslig och reaktiv hud - 45 minuter, 695 kr',
      'Skonsamt upplägg utifrån hudens aktuella tillstånd',
      'Fokus på att lugna och stärka hudbarriären',
      'Råd om balanserad hudvård mellan behandlingarna',
    ],
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: '45 minuter',
      paKliniken: 'Behandlingen anpassas efter hudens tolerans',
      tillbakaTillVardagen: 'Direkt',
      antalBehandlingar: 'Varierar efter hudens tillstånd och behov',
      risker: 'Tillfällig rodnad eller känslighet kan förekomma',
      efterbehandling: 'Följ en lugn och balanserad hudvårdsrutin',
      undvik: 'Överdriven exfoliering och för många aktiva produkter',
      pris: '695 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Hur vet jag om jag har känslig hud?', answer: 'Vanliga upplevelser är rodnad, stramhet, irritation, värmekänsla, torrhet eller att huden snabbt reagerar på produkter.' },
      { question: 'Passar behandlingen torr hud?', answer: 'Den kan passa när torrhet eller stramhet förekommer tillsammans med känslighet och obalans.' },
      { question: 'Kan känslig hud göra Hydrafacial?', answer: 'Det beror på hudens tillstånd. Boka hudanalys om du är osäker.' },
      { question: 'Kan jag göra kemisk peeling?', answer: 'Alla peelingar passar inte alla hudtillstånd. Bedömning görs individuellt.' },
      { question: 'Vad kostar behandlingen?', answer: 'Behandlingen kostar 695 kr.' },
      { question: 'Hur lång är behandlingen?', answer: 'Behandlingen tar 45 minuter.' },
    ],
  },
  {
    slug: 'pigmentering-stockholm',
    title: 'Pigmentering & ojämn hudton',
    pageTitle: 'Behandling av pigmentfläckar och ojämn hudton i Stockholm',
    summary: 'Individuellt anpassad behandling för pigmentfläckar, solskador och ojämn hudton i Stockholm. 30 minuter, 795 kr.',
    intro:
      'Pigmentförändringar kan visa sig som mörkare områden, solfläckar eller en generellt ojämn hudton. Dermalaser erbjuder individuellt anpassad behandling för dig som vill arbeta med hudens klarhet, jämnhet och lyster utan att stressa huden i onödan. Behandlingen tar 30 minuter och kostar 795 kr.',
    points: [
      'Mörkare pigmentfläckar och solfläckar',
      'Pigmentering efter finnar och inflammation',
      'Ojämn hudton och minskad lyster',
      'Pigmentförändringar som blivit tydligare efter sol',
      'Hud som behöver ett mer jämnt och långsiktigt upplägg',
    ],
    items: [
      'Pigmentbehandling - 30 minuter, 795 kr',
      'Individuell bedömning av pigmentförändringarna',
      'Råd om solskydd och hudvård mellan behandlingarna',
      'Möjlighet att diskutera kemisk peeling eller annan hudförnyande behandling',
    ],
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: '30 minuter',
      paKliniken: 'Behandlingen anpassas efter pigmenteringens typ och hudens tillstånd',
      tillbakaTillVardagen: 'Direkt, individuell eftervård rekommenderas',
      antalBehandlingar: 'Varierar beroende på pigmentförändring och hudens respons',
      risker: 'Tillfällig rodnad eller känslighet kan förekomma',
      efterbehandling: 'Använd solskydd och följ rekommenderad hemvård',
      undvik: 'UV-exponering och produkter som stressar huden',
      pris: '795 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Kan pigmentfläckar försvinna helt?', answer: 'Resultat varierar beroende på typen av pigmentförändring, hudens förutsättningar och hur den reagerar på behandling.' },
      { question: 'Kan kemisk peeling användas vid pigmentering?', answer: 'Vissa peelingar kan vara relevanta vid ojämn hudton och pigmentering efter individuell bedömning.' },
      { question: 'Är BioRePeel ett alternativ?', answer: 'Dermalaser erbjuder BioRePeelCl3 och anger pigmentering som ett av användningsområdena.' },
      { question: 'Kan solen göra pigmentfläckar tydligare?', answer: 'Ja, UV-exponering kan bidra till att flera former av pigmentering blir mer framträdande.' },
      { question: 'Vad kostar behandlingen?', answer: 'Pigmentbehandlingen kostar 795 kr.' },
      { question: 'Hur lång är behandlingen?', answer: 'Behandlingen tar 30 minuter.' },
    ],
  },
  {
    slug: 'signature-hudbehandling-stockholm',
    title: 'Signature Premium Hudbehandling',
    pageTitle: 'Premium ansiktsbehandling i Stockholm - Signature Dermalaser',
    summary: 'Komplett premiumbehandling med hudanalys, Hydrafacial, anpassad peeling och vid behov Carbon Peel. 45 minuter, 1 999 kr.',
    intro:
      'Signature Premium är en komplett, skräddarsydd hudbehandling som kombinerar flera avancerade tekniker i samma besök. Behandlingen inleds med hudanalys och djuprengörande Hydrafacial, följt av individuellt vald kemisk peeling. Den kan även kompletteras med Carbon Peel när det passar hudens behov. Behandlingen tar 45 minuter och kostar 1 999 kr.',
    points: [
      'Professionell hudanalys',
      'Hydrafacial',
      'Individuellt vald kemisk peeling',
      'Carbon Peel vid behov och när huden är lämplig',
    ],
    items: [
      'Signature Premium Hudbehandling - 45 minuter, 1 999 kr',
      'Hudanalys och djuprengörande Hydrafacial',
      'Peeling vald efter hudens aktuella behov',
      'Möjlighet till Carbon Peel när huden är lämplig',
    ],
    image: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: '45 minuter',
      paKliniken: 'Flera hudvårdande moment kombineras i samma besök',
      tillbakaTillVardagen: 'Direkt, individuell eftervård rekommenderas',
      antalBehandlingar: 'Kan bokas som en komplett behandling efter hudens behov',
      risker: 'Tillfällig rodnad eller känslighet kan förekomma',
      efterbehandling: 'Följ rekommenderad hemvård och använd solskydd',
      undvik: 'Aktiva produkter enligt individuell rekommendation efter behandlingen',
      pris: '1 999 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Vad ingår i Signature Premium?', answer: 'Hudanalys, Hydrafacial och individuellt vald kemisk peeling. Carbon Peel kan läggas till beroende på huden.' },
      { question: 'Är behandlingen samma för alla?', answer: 'Nej. Den anpassas individuellt efter hudens aktuella tillstånd och dina mål.' },
      { question: 'Hur lång är behandlingen?', answer: 'Behandlingen tar 45 minuter.' },
      { question: 'Vad kostar den?', answer: 'Signature Premium kostar 1 999 kr.' },
      { question: 'Är den mer omfattande än vanlig Hydrafacial?', answer: 'Ja. Signature kombinerar flera metoder medan Hydrafacial är en separat behandling med fokus på rengöring, exfoliering och återfuktning.' },
      { question: 'Kan jag boka om jag inte vet vad huden behöver?', answer: 'Ja. Hudanalys ingår i behandlingen.' },
    ],
  },
  {
    slug: 'ansiktsbehandling-stockholm',
    title: 'Klassisk Hudbehandling',
    pageTitle: 'Klassisk ansiktsbehandling i Stockholm',
    summary: 'Professionell klassisk ansiktsbehandling i Stockholm med exfoliering, mask, LED och individuellt anpassad hudvård. 45 minuter, 795 kr.',
    intro:
      'En professionell ansiktsbehandling behöver inte alltid vara avancerad. Dermalasers klassiska hudbehandling fokuserar på hudens grundläggande behov och anpassas individuellt efter hudtyp och aktuellt hudtillstånd. Behandlingen tar 45 minuter och kostar 795 kr.',
    points: [
      'Ångbehandling',
      'Högfrekvens',
      'Skonsam exfoliering och avlägsnande av döda hudceller',
      'Individuellt anpassad ansiktsmask',
      'LED-ljusterapi',
    ],
    items: [
      'Klassisk ansiktsbehandling - 45 minuter, 795 kr',
      'Ånga och högfrekvens',
      'Skonsam exfoliering och avlägsnande av döda hudceller',
      'Individuellt anpassad ansiktsmask och LED-ljusterapi',
    ],
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: '45 minuter',
      paKliniken: 'Behandlingen anpassas efter hudtyp och aktuellt hudtillstånd',
      tillbakaTillVardagen: 'Direkt',
      antalBehandlingar: 'Passar som regelbundet professionellt underhåll',
      risker: 'Tillfällig rodnad eller känslighet kan förekomma',
      efterbehandling: 'Följ rekommenderad hudvård efter behandlingen',
      undvik: 'Aggressiv exfoliering om huden känns känslig efteråt',
      pris: '795 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Vad ingår?', answer: 'Ånga, högfrekvens, exfoliering, anpassad mask och LED-ljusterapi.' },
      { question: 'Vad kostar behandlingen?', answer: 'Behandlingen kostar 795 kr.' },
      { question: 'Hur lång tid tar den?', answer: 'Behandlingen tar 45 minuter.' },
      { question: 'Är detta en djuprengörande ansiktsbehandling?', answer: 'Behandlingen innehåller rengörande och exfolierande moment. Vid större fokus på tilltäppt hud kan Hydrafacial eller Carbon Peel vara alternativ.' },
      { question: 'Vad är skillnaden mot Signature Premium?', answer: 'Signature Premium kombinerar flera mer avancerade tekniker, bland annat Hydrafacial och peeling.' },
    ],
  },
  {
    slug: 'kemisk-peeling-stockholm',
    title: 'Kemisk peeling',
    pageTitle: 'Kemisk peeling i Stockholm - PRX-T33, BioRePeel och Glycolic',
    summary: 'Kemisk peeling i Stockholm med PRX-T33, BioRePeel eller individuellt vald peeling för lyster, struktur, pigmentering och oren hud. 45 minuter, 1 195 kr.',
    intro:
      'Kemisk peeling används för kontrollerad hudförnyelse och kan anpassas efter flera olika hudproblem. Dermalaser erbjuder bland annat PRX-T33, BioRePeelCl3 och glycolic/glykolsyra. Rätt alternativ väljs efter hudtyp, hudtillstånd och mål. Behandlingen tar 45 minuter och kostar 1 195 kr.',
    points: [
      'Ojämn hudstruktur',
      'Glåmighet',
      'Pigmentering och ojämn hudton',
      'Fina linjer',
      'Synliga porer',
      'Oren och tilltäppt hud',
    ],
    items: [
      'Kemisk peeling - 45 minuter, 1 195 kr',
      'PRX-T33',
      'BioRePeelCl3',
      'Glycolic/glykolsyra',
      'Individuellt vald peeling efter hudanalys',
    ],
    image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: '45 minuter',
      paKliniken: 'Peeling väljs efter hudtyp, tolerans och mål',
      tillbakaTillVardagen: 'Varierar beroende på vald peeling',
      antalBehandlingar: 'Planeras efter hudens tillstånd och önskat resultat',
      risker: 'Rodnad, känslighet eller fjällning kan förekomma beroende på peeling',
      efterbehandling: 'Följ rekommenderad hemvård och använd solskydd',
      undvik: 'UV-exponering och aktiva produkter enligt individuell rekommendation',
      pris: '1 195 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Vad kostar kemisk peeling?', answer: 'Kemisk peeling kostar 1 195 kr.' },
      { question: 'Hur lång är behandlingen?', answer: 'Behandlingen tar 45 minuter.' },
      { question: 'Vilka peelingar erbjuder Dermalaser?', answer: 'PRX-T33, BioRePeelCl3 och glycolic/glykolsyra finns listade.' },
      { question: 'Kan peeling användas mot pigmentering?', answer: 'Vissa peelingar kan vara relevanta vid ojämn hudton och pigmentering efter individuell bedömning.' },
      { question: 'Kan peeling hjälpa vid porer?', answer: 'BioRePeel används bland annat med fokus på förstorade porer och ojämn struktur.' },
      { question: 'Kan kemisk peeling användas vid akne?', answer: 'Vissa peelingar kan passa oren eller aknebenägen hud, men aktiv och känslig hud behöver bedömas individuellt.' },
      { question: 'PRX-T33 eller BioRePeel?', answer: 'Det beror på huden, målet och önskad behandlingsnivå.' },
    ],
  },
  {
    slug: 'hydrafacial-stockholm',
    title: 'Hydrafacial',
    pageTitle: 'Hydrafacial i Stockholm - djuprengöring, återfuktning och lyster',
    summary: 'Boka Hydrafacial i Stockholm för djuprengöring, exfoliering och återfuktning. För porer, glåmig och yttorr hud. 30 minuter, 895 kr.',
    intro:
      'Hydrafacial kombinerar rengöring, exfoliering och intensiv återfuktning i en skonsam behandling som anpassas efter huden. Den passar särskilt dig som vill arbeta med tilltäppt hud, ojämn struktur, glåmighet, yttorrhet eller hud som känns trött och obalanserad. Behandlingen tar 30 minuter och kostar 895 kr.',
    points: [
      'Djuprengöring och exfoliering',
      'Tilltäppta porer och oren hud',
      'Ojämn hudstruktur och glåmighet',
      'Yttorr eller trött hud',
      'Återfuktning och förbättrad lyster',
    ],
    items: [
      'Hydrafacial - 30 minuter, 895 kr',
      'Rengöring och exfoliering',
      'Intensiv återfuktning',
      'Anpassning efter hudens aktuella behov',
    ],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: '30 minuter',
      paKliniken: 'Behandlingen anpassas efter hudens behov',
      tillbakaTillVardagen: 'Direkt',
      antalBehandlingar: 'Kan utföras regelbundet när huden tolererar det',
      risker: 'Tillfällig rodnad eller känslighet kan förekomma',
      efterbehandling: 'Följ rekommenderad hudvård och använd solskydd',
      undvik: 'Aggressiv exfoliering direkt efter behandlingen',
      pris: '895 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Vad kostar Hydrafacial?', answer: 'Hydrafacial kostar 895 kr.' },
      { question: 'Hur lång tid tar behandlingen?', answer: 'Behandlingen tar 30 minuter.' },
      { question: 'Passar Hydrafacial torr hud?', answer: 'Den innehåller återfuktande moment och kan vara relevant för yttorr hud.' },
      { question: 'Passar Hydrafacial pormaskar?', answer: 'Den används bland annat vid tilltäppt hud.' },
      { question: 'Får man lyster direkt?', answer: 'Dermalaser beskriver fin lyster direkt efter behandlingen, men resultat varierar mellan personer.' },
      { question: 'Kan Hydrafacial göras regelbundet?', answer: 'Ja, den kan ingå i en återkommande hudvårdsrutin när huden tolererar det.' },
      { question: 'Vad är skillnaden mot Carbon Peel?', answer: 'Hydrafacial fokuserar mer på rengöring och fukt, medan Carbon Peel fokuserar mer på talg, porer och klarhet.' },
    ],
  },
  {
    slug: 'carbon-peel-stockholm',
    title: 'Carbon Peel',
    pageTitle: 'Carbon Peel i Stockholm - Hollywood Peel för porer och oren hud',
    summary: 'Carbon Peel i Stockholm för stora porer, fet hud, orenheter och ojämn hudstruktur. Djuprengörande behandling. 45 minuter, 1 095 kr.',
    intro:
      'Carbon Peel är en resultatinriktad behandling för dig som vill arbeta med tilltäppt hud, synliga porer, ojämn hudstruktur eller hud som känns fet och obalanserad. Behandlingen kallas också Hollywood Peel. Den tar 45 minuter och kostar 1 095 kr.',
    points: [
      'Tilltäppt hud och orenheter',
      'Synliga eller stora porer',
      'Fet och blank hud',
      'Ojämn hudstruktur',
      'Hud som känns obalanserad och saknar klarhet',
    ],
    items: [
      'Carbon Peel - 45 minuter, 1 095 kr',
      'Djuprengörande behandling med fokus på talg och hudklarhet',
      'Individuellt upplägg efter hudens aktuella behov',
      'Hollywood Peel är ett annat vanligt namn för behandlingen',
    ],
    image: 'https://images.unsplash.com/photo-1519415943484-9fa1873496d4?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: '45 minuter',
      paKliniken: 'Behandlingen anpassas efter hudens tillstånd',
      tillbakaTillVardagen: 'Direkt, tillfällig rodnad kan förekomma',
      antalBehandlingar: 'Långsiktigt resultat beror på hudens förutsättningar och regelbundenhet',
      risker: 'Tillfällig rodnad eller känslighet kan förekomma',
      efterbehandling: 'Följ rekommenderad hudvård och använd solskydd',
      undvik: 'Aggressiv exfoliering direkt efter behandlingen',
      pris: '1 095 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Vad är Carbon Peel?', answer: 'En behandling med fokus på tilltäppt hud, porer, talg, orenheter och hudklarhet.' },
      { question: 'Är Carbon Peel samma som Hollywood Peel?', answer: 'Namnen används ofta för samma typ av behandling.' },
      { question: 'Hur lång är behandlingen?', answer: 'Behandlingen tar 45 minuter.' },
      { question: 'Vad kostar den?', answer: 'Carbon Peel kostar 1 095 kr.' },
      { question: 'Passar den fet hud?', answer: 'Ja, Dermalaser rekommenderar den särskilt för hud som känns fet och obalanserad.' },
      { question: 'Kan den användas vid stora porer?', answer: 'Synliga porer är ett av de områden behandlingen är inriktad mot.' },
      { question: 'Hydrafacial eller Carbon Peel?', answer: 'Det beror på huden och målet. Börja med hudanalys om du är osäker.' },
    ],
  },
  {
    slug: 'laser-harborttagning-stockholm',
    title: 'Diodlaser hårborttagning',
    pageTitle: 'Laser hårborttagning i Stockholm med diodlaser',
    summary: 'Diodlaser för långsiktig hårreducering i Stockholm. Behandla ansikte, armhålor, bikini, ben, rygg och fler områden. Priser från 495 kr.',
    intro:
      'Dermalaser erbjuder diodlaser för långsiktig reducering av oönskad hårväxt. Behandlingen anpassas efter hudtyp, hårtyp och behandlingsområde. Eftersom hårstrån befinner sig i olika tillväxtfaser behövs flera behandlingar för bästa resultat. Litet område kostar 495 kr, mellanområde 995 kr och större område 1 495 kr.',
    points: [
      'Litet område - 495 kr: överläpp, armhåla, haka, polisonger, hals, mellan bryn, kinder och bikinilinje',
      'Mellanområde - 995 kr: brasiliansk bikini, halva armar, halva ben, axlar, nacke och mage',
      'Större område - 1 495 kr: hela ben, hela armar, rygg, bröst och större kombinationsområden',
      'Ansikte, armhålor, bikini, ben och fler behandlingsområden',
    ],
    items: [
      'Litet område - 495 kr',
      'Mellanområde - 995 kr',
      'Större område - 1 495 kr',
      'Diodlaser anpassad efter hudtyp, hårtyp och område',
    ],
    image: 'https://images.unsplash.com/photo-1601058268499-e52658b8bb88?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: 'Varierar beroende på behandlingsområde',
      paKliniken: 'Behandlingen anpassas efter hudtyp, hårtyp och område',
      tillbakaTillVardagen: 'Vanligtvis direkt',
      antalBehandlingar: 'Flera behandlingar behövs eftersom hårstrån är i olika tillväxtfaser',
      risker: 'Tillfällig rodnad eller känslighet kan förekomma',
      efterbehandling: 'Följ rekommendationer om sol och hudvård efter behandlingen',
      undvik: 'Raka området före besöket och undvik plockning mellan behandlingarna enligt råd',
      pris: 'Från 495 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Är laser hårborttagning permanent?', answer: 'Tjänsten beskrivs som långsiktig hårreducering eftersom resultat varierar mellan personer och återväxt kan förekomma.' },
      { question: 'Hur många behandlingar behövs?', answer: 'Flera behandlingar behövs eftersom hårstrån befinner sig i olika tillväxtfaser.' },
      { question: 'Måste jag raka mig innan?', answer: 'Ja. Området ska vara rakat före behandlingen.' },
      { question: 'Vad händer om jag inte rakar mig?', answer: 'Dermalaser anger 100 kr extra om rakning behöver göras på plats.' },
      { question: 'Vad kostar laser hårborttagning?', answer: 'Från 495 kr för litet område, 995 kr för mellanområde och 1 495 kr för större område.' },
      { question: 'Kan jag behandla armhålor?', answer: 'Ja.' },
      { question: 'Kan jag lasra bikinilinjen?', answer: 'Ja, bikinilinje är litet område och brasiliansk bikini är mellanområde.' },
      { question: 'Kan jag behandla ansiktet?', answer: 'Ja, flera mindre ansiktsområden finns listade.' },
    ],
  },
  {
    slug: 'co2-laser-stockholm',
    title: 'CO2 Laser Resurfacing',
    pageTitle: 'CO2 Laser i Stockholm - avancerad hudförnyelse',
    summary: 'CO2 Laser Resurfacing i Stockholm för akneärr, ojämn struktur, fina linjer, pigmentförändringar och solskadad hud. Individuell bedömning. 60 minuter, 4 500 kr.',
    intro:
      'CO2 Laser Resurfacing är en mer avancerad behandling för dig som vill arbeta med hudstruktur och hudkvalitet på en djupare nivå. Dermalaser använder fraktionerad CO2-laser för att stimulera hudens naturliga reparationsprocess och kollagenremodellering. Behandlingen tar 60 minuter och kostar 4 500 kr.',
    points: [
      'Akneärr',
      'Ojämn hudstruktur',
      'Fina linjer och rynkor',
      'Pigmentförändringar',
      'Solskadad hud',
    ],
    items: [
      'CO2 Laser Resurfacing - 60 minuter, 4 500 kr',
      'Fraktionerad CO2-laser',
      'Professionell hudbedömning före behandlingen',
      'Individuell plan för hudstruktur och hudkvalitet',
    ],
    image: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?auto=format&fit=crop&w=1800&q=85',
    facts: {
      behandlingstid: '60 minuter',
      paKliniken: 'Professionell hudbedömning görs före behandling',
      tillbakaTillVardagen: 'Återhämtningstid behövs',
      antalBehandlingar: 'Planeras individuellt efter hudens mål och tillstånd',
      risker: 'Rodnad, svullnad och känslighet kan förekomma under läkning',
      efterbehandling: 'Följ noggrant rekommenderad eftervård och använd solskydd',
      undvik: 'Sol och aktiva produkter under återhämtningsperioden enligt rekommendation',
      pris: '4 500 kr',
      betalning: 'Kort eller Swish på plats',
    },
    faq: [
      { question: 'Vad är CO2 Laser Resurfacing?', answer: 'En avancerad fraktionerad laserbehandling för kontrollerad hudförnyelse.' },
      { question: 'Kan CO2-laser användas för akneärr?', answer: 'Ja, akneärr är ett av de användningsområden Dermalaser anger.' },
      { question: 'Kan behandlingen användas vid fina linjer?', answer: 'Ja, fina linjer och rynkor finns angivna bland möjliga behandlingsområden.' },
      { question: 'Finns återhämtningstid?', answer: 'Ja. Detta är en intensivare behandling och innebär en återhämtningsperiod.' },
      { question: 'Ser man slutresultatet direkt?', answer: 'Nej. Resultatet utvecklas gradvis i takt med läkning och kollagenremodellering.' },
      { question: 'Vad kostar behandlingen?', answer: 'CO2 Laser Resurfacing kostar 4 500 kr.' },
      { question: 'Hur lång tid tar den?', answer: 'Behandlingen tar 60 minuter.' },
      { question: 'Behövs hudbedömning innan?', answer: 'Ja. Dermalaser anger att en professionell hudbedömning görs före behandling.' },
    ],
  },
] as const;

export const serviceLinks = services.map(({ title, summary }) => [title, summary]);
